---
title: Are You in the Room? A Framework for Sortition and Representation
author: Daniel Loza
date: today
toc: false
format: # Use only one of these
  presentation-revealjs+letterbox: default
---

```{r}
#| label: load-packages
#| include: false
library(knitr)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)
library(UpSetR)
library(here)
library(tidyverse)
require(ggmosaic)
library(patchwork)
options(width = 70)
```

# Are you in the room?

## Sortition and representation

- Used since ancient times, but recently gaining renewed interest
- Descriptively representative
- Enables greater diversity, inclusion and representation of communities

## The algorithm

- LexiMin, or Lexicographic Maximin
- Iteratively selects individuals to maximise the minimum likelihood of selection across traits of interest
- Can be applied to any set of traits and any population

## The process

- Define a population and traits of interest
- Request expressions of interest from a random subset of the population
- Feed respondents into the sortition algorithm
- Use the generated panel for deliberation and decision-making

# But where do we assess the representativeness?

## Improving the process

- Visualising to improve transparency
- Measuring performance and how extreme cases are handled
- Building a dashboard and framework to encourage evaluation of resulting panels against starting populations or prior stages

## How will we do this?

- Simulate a population and traits of interest
- Simulate the process of requesting expressions of interest and selection
- Visualise the results and build a dashboard to evaluate representativeness

## Specific tests

- Populations (N) of size 10000, 50000 and 100000
- Traits of interest (k) of 3 and 5, as these are common in practice
- Population distributions of Uniform, Gaussian, and Beta, to show how the algorithm performs with different levels of skew and complexity
- Uniform and varied response rates of 10%, 30%, and 50%, to show how the algorithm performs when different groups are more or less likely to respond
- Extreme cases where one or more groups are particularly small or large, to show how the algorithm performs when certain groups are more or less likely to be represented

## Why is this important? A small test case.

